### ISSUE TITLE
Need Sample Use Source Code Example

### ISSUE THREAD

**Issue by Bulzi-Robb** [gktval/Maui-GeolocatorPlugin#4]
Travis Yeik @gktval ,

Is it possible to get sample source code built from a `dotnet new MauiApp` starting point.
I'm not having great success trying to convert James's Sample source code for GeolocatorPlugIn for Xamarin.
Having the ported sample from Xamarin to .NET MAUI would be very helpful, especially for getting the background locations changes setup.

**Comment by mcodo** [comment]
Any feedback on this? I an also struggeling with the Xamarin code :-o

**Comment by gktval** [comment]
I will put something together this week.

**Comment by gktval** [comment]
I added a Samples project built in Maui that demonstrates how to use the plugin. It should work for both Android and iOS.

https://github.com/gktval/Maui-GeolocatorPlugin/tree/main/Sample
