### ISSUE TITLE
Location not working when the app is minimized

### ISSUE THREAD

**Issue by cissemy** [gktval/Maui-GeolocatorPlugin#8]
Hi
The app stopping sending the location when it is minimized or running under background.
How to fix that ?

**Comment by gktval** [comment]
You have to create a background service. Then when you start the gps, start your background service.
 There are several places to find examples for creating background services. Here is one I used:
https://stackoverflow.com/questions/71259615/how-to-create-a-background-service-in-net-maui

**Comment by cissemy** [comment]
Hi
I tried that but I am getting:
Android.App.MissingForegroundServiceTypeException: 'Starting FGS without a type  callerApp=ProcessRecord{2a6aae5 17133:com.companyname.mauiapp6/u0a192} targetSDK=34'
Thanks

**Comment by gktval** [comment]
Hi, if you're having difficulties setting up the foreground service, I would ask on a forum specific to the problems you are having.
